# Generated by Django 3.2.5 on 2022-06-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Salary', models.IntegerField()),
                ('Location', models.CharField(max_length=200)),
                ('Position', models.CharField(max_length=200)),
            ],
        ),
    ]
