# Generated by Django 3.2.5 on 2022-06-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Trainer', models.CharField(max_length=40)),
                ('Location', models.CharField(max_length=50)),
                ('Days', models.IntegerField()),
            ],
        ),
    ]
