# Generated by Django 3.2.5 on 2022-05-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.IntegerField()),
                ('EmpName', models.CharField(max_length=100)),
                ('EmpSal', models.IntegerField()),
                ('EmpAdd', models.CharField(max_length=100)),
            ],
        ),
    ]
